# Site settings
theme: jekyll-theme-slate
title: Machine Learning for Healthcare
email: hyunkwanglee@g.harvard.edu
description: "PhD in Eletrical Engineering at Harvard SEAS"
baseurl: ""
url: "http://hyunkwang.github.io"
twitter_username: hyunkwang_lee
github_username: hyunkwang
